name: Deployment to Sandbox
on:
  push:
    paths:
      - force-app/**
    branches:
      - Dev1Team
jobs:
  deployment-to-sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: >
          wget
          https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz

          mkdir ~/sfdx

          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1

          echo "$HOME/sfdx/bin" >> $GITHUB_PATH

          ~/sfdx/bin/sfdx version
      - name: Populate auth file with SFDX_URL secret of target org
        run: |
          echo ${{ secrets.DEV2_URL}} > ./DEV2_URL.txt
      - name: Authenticate to target Org
        run: sfdx auth:sfdxurl:store -f ./DEV2_URL.txt -s -a targetOrg
      - name: Deployment - run all tests
        run: >
          sfdx force:source:deploy -p "force-app"  --testlevel RunLocalTests --json
          sf org assign permset -n ebikes
          sf data tree import -p ./data/sample-data-plan.json
          sf community publish -n E-Bikes
          sf project deploy start --metadata-dir=guest-profile-metadata -w 10
          sf org open
